export {
  stateDistance,
  collapseScore,
  repairCapacity,
  detectCyclePeriod,
  estimateDivergenceRate,
  trajectoryMetrics,
} from './analysis';
export {
  applyConflictTransition,
  evaluateActionUtilities,
  getAvailableActions,
  getObservationForPlayer,
  resolveProtocolStep,
  runConflictTrajectory,
  selectDominantAction,
  updateStrategyProfileReplicator,
  validateJointAction,
} from './engine';
export {
  createTrustExchangeProtocol,
  defaultConflictAgentState,
  defaultConflictRelationState,
  TRUST_EXCHANGE_ACTION_ORDER,
} from './trustExchange';
export type {
  ActionUtilityBreakdown,
  AgentDelta,
  ConflictAction,
  ConflictActionId,
  ConflictAgentState,
  ConflictEnvironmentKey,
  ConflictEnvironmentState,
  ConflictHistoryEvent,
  ConflictObservation,
  ConflictPhase,
  ConflictPlayerId,
  ConflictProtocol,
  ConflictProtocolId,
  ConflictRelationKey,
  ConflictRelationState,
  ConflictRole,
  ConflictScalarKey,
  ConflictState,
  ConflictStepResult,
  ConflictValidationError,
  ConflictValidationErrorCode,
  ConflictOutcome,
  RelationDelta,
  Result,
  StrategyProfile,
  TrajectoryMetrics,
  TrustExchangeActionId,
} from './types';

