import type { IntentSpecV1 } from './types';

export const INTENT_SPECS_V1: IntentSpecV1[] = [
  {
    id: 'withdraw',
    family: 'movement',
    label: 'Отойти / снизить вовлечённость',
    description: 'Уменьшить непосредственный риск или выйти из перегрузки.',
    targeting: 'self',
    sourceGoals: ['reduce_self_threat', 'restore_self_control', 'deescalate_interaction'],
    preconditions: [],
    blockers: [],
    priorityBase: 0.05,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'reduce_self_threat', weight: 0.9, clamp: [0, 1.5] },
      { kind: 'weighted_goal', goalId: 'restore_self_control', weight: 0.7, clamp: [0, 1.2] },
      { kind: 'weighted_metric', metric: 'hazard', weight: 0.4, clamp: [0, 0.8] },
    ],
    groundingHints: ['move', 'retreat', 'wait'],
    tags: ['survival', 'deescalation'],
  },

  {
    id: 'seek_cover',
    family: 'movement',
    label: 'Искать укрытие',
    description: 'Перейти в более безопасную позицию.',
    targeting: 'location',
    sourceGoals: ['reduce_self_threat', 'recover_resources'],
    preconditions: [],
    blockers: [],
    priorityBase: 0.04,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'reduce_self_threat', weight: 1.0, clamp: [0, 1.6] },
      { kind: 'weighted_metric', metric: 'hazard', weight: 0.6, clamp: [0, 1.0] },
    ],
    groundingHints: ['move', 'move_xy', 'move_cell'],
    tags: ['cover'],
  },

  {
    id: 'move_to_safe_place',
    family: 'movement',
    label: 'Перейти в безопасное место',
    description: 'Сменить позицию ради снижения угрозы и восстановления контроля.',
    targeting: 'location',
    sourceGoals: ['reduce_self_threat', 'restore_self_control', 'recover_resources'],
    preconditions: [],
    blockers: [],
    priorityBase: 0.03,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'reduce_self_threat', weight: 0.9, clamp: [0, 1.4] },
      { kind: 'weighted_goal', goalId: 'restore_self_control', weight: 0.5, clamp: [0, 0.8] },
    ],
    groundingHints: ['move', 'move_xy', 'move_cell'],
    tags: ['relocation'],
  },

  {
    id: 'warn_group',
    family: 'communication',
    label: 'Предупредить группу',
    description: 'Сообщить о риске другим участникам.',
    targeting: 'group',
    sourceGoals: ['reduce_self_threat', 'maintain_contact_channel'],
    preconditions: [
      {
        kind: 'any',
        conditions: [
          { kind: 'recent_event', eventKinds: ['hazard', 'attack', 'threat', 'blocked'], maxAge: 6 },
          { kind: 'appraisal_tag', tags: ['danger_to_self'], minScore: 0.35 },
        ],
      },
    ],
    blockers: [
      { kind: 'metric', metric: 'self_stress', op: '>=', value: 0.98 },
    ],
    priorityBase: 0.03,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'reduce_self_threat', weight: 0.6, clamp: [0, 1.0] },
      { kind: 'weighted_metric', metric: 'hazard', weight: 0.5, clamp: [0, 0.9] },
    ],
    groundingHints: ['talk', 'signal', 'share'],
    dialogueAct: 'warn',
    desiredEffect: 'increase_compliance',
    tags: ['communication', 'hazard'],
  },

  {
    id: 'reassure_target',
    family: 'communication',
    label: 'Успокоить цель',
    description: 'Снизить панику или дистресс другого персонажа.',
    targeting: 'other',
    sourceGoals: ['stabilize_other', 'preserve_cooperation', 'maintain_trust_signal', 'deescalate_interaction'],
    preconditions: [
      { kind: 'target_exists' },
      {
        kind: 'any',
        conditions: [
          { kind: 'appraisal_tag', tags: ['target_distress', 'target_injury'], minScore: 0.3, targetRole: 'target' },
          { kind: 'metric', metric: 'target_stress', op: '>=', value: 0.45 },
        ],
      },
      { kind: 'target_communicable', maxDistance: 4 },
      { kind: 'not_repeated', actionIds: ['comfort', 'talk', 'reassure_target'], horizon: 4, maxCount: 1 },
    ],
    blockers: [],
    priorityBase: 0.06,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'stabilize_other', weight: 0.9, clamp: [0, 1.5] },
      { kind: 'weighted_metric', metric: 'target_stress', weight: 0.4, clamp: [0, 0.8] },
      { kind: 'weighted_metric', metric: 'closeness', weight: 0.25, clamp: [0, 0.5] },
    ],
    groundingHints: ['comfort', 'talk', 'share'],
    dialogueAct: 'reassure',
    desiredEffect: 'reduce_panic',
    tags: ['care', 'social_support'],
  },

  {
    id: 'assist_target',
    family: 'care',
    label: 'Помочь цели',
    description: 'Оказать практическую помощь нуждающемуся персонажу.',
    targeting: 'other',
    sourceGoals: ['stabilize_other'],
    preconditions: [
      { kind: 'target_exists' },
      {
        kind: 'any',
        conditions: [
          { kind: 'appraisal_tag', tags: ['target_injury', 'target_distress'], minScore: 0.35, targetRole: 'target' },
          { kind: 'instrumental_need', minValue: 0.35 },
        ],
      },
      { kind: 'target_reachable', maxDistance: 6 },
    ],
    blockers: [],
    priorityBase: 0.05,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'stabilize_other', weight: 1.0, clamp: [0, 1.6] },
      { kind: 'weighted_metric', metric: 'utility_of_target', weight: 0.35, clamp: [0, 0.6] },
    ],
    groundingHints: ['help', 'guard', 'escort', 'treat'],
    tags: ['care'],
  },

  {
    id: 'escort_target',
    family: 'care',
    label: 'Сопроводить цель',
    description: 'Вывести или перевести другого в более безопасное место.',
    targeting: 'other',
    sourceGoals: ['stabilize_other'],
    preconditions: [
      { kind: 'target_exists' },
      { kind: 'target_reachable', maxDistance: 5 },
    ],
    blockers: [],
    priorityBase: 0.03,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'stabilize_other', weight: 0.7, clamp: [0, 1.1] },
      { kind: 'weighted_metric', metric: 'hazard', weight: 0.35, clamp: [0, 0.7] },
    ],
    groundingHints: ['escort', 'guard', 'move'],
    tags: ['movement', 'care'],
  },

  {
    id: 'treat_target',
    family: 'care',
    label: 'Лечить / стабилизировать цель',
    description: 'Прямо воздействовать на ранение или физическое состояние цели.',
    targeting: 'other',
    sourceGoals: ['stabilize_other'],
    preconditions: [
      { kind: 'target_exists' },
      {
        kind: 'any',
        conditions: [
          { kind: 'appraisal_tag', tags: ['target_injury'], minScore: 0.4, targetRole: 'target' },
          { kind: 'metric', metric: 'target_health', op: '<=', value: 0.65 },
        ],
      },
      { kind: 'target_reachable', maxDistance: 3 },
    ],
    blockers: [],
    priorityBase: 0.05,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'stabilize_other', weight: 0.9, clamp: [0, 1.4] },
      { kind: 'weighted_metric', metric: 'target_health', weight: -0.5, clamp: [-0.5, 0] },
    ],
    groundingHints: ['treat', 'help'],
    tags: ['medical', 'care'],
  },

  {
    id: 'ask_fact',
    family: 'epistemic',
    label: 'Спросить факт',
    description: 'Получить недостающую информацию у другого.',
    targeting: 'other',
    sourceGoals: ['verify_claim', 'maintain_contact_channel'],
    preconditions: [
      { kind: 'target_exists' },
      { kind: 'target_communicable', maxDistance: 5 },
      {
        kind: 'any',
        conditions: [
          { kind: 'metric', metric: 'uncertainty', op: '>=', value: 0.45 },
          { kind: 'appraisal_tag', tags: ['information_gap', 'suspicion'], minScore: 0.3 },
        ],
      },
    ],
    blockers: [],
    priorityBase: 0.03,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'verify_claim', weight: 1.0, clamp: [0, 1.5] },
      { kind: 'weighted_metric', metric: 'uncertainty', weight: 0.5, clamp: [0, 0.8] },
    ],
    groundingHints: ['question_about', 'talk', 'share'],
    dialogueAct: 'request_help',
    desiredEffect: 'obtain_commitment',
    tags: ['epistemic', 'dialogue'],
  },

  {
    id: 'observe_target',
    family: 'epistemic',
    label: 'Наблюдать цель',
    description: 'Проверить поведение цели без немедленного разговора.',
    targeting: 'other',
    sourceGoals: ['verify_claim'],
    preconditions: [{ kind: 'target_exists' }],
    blockers: [],
    priorityBase: 0.02,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'verify_claim', weight: 0.7, clamp: [0, 1.1] },
      { kind: 'weighted_metric', metric: 'uncertainty', weight: 0.4, clamp: [0, 0.7] },
    ],
    groundingHints: ['observe', 'move'],
    tags: ['epistemic'],
  },

  {
    id: 'inspect_location',
    family: 'epistemic',
    label: 'Проверить локацию',
    description: 'Уточнить состояние места, маршрута или источника угрозы.',
    targeting: 'location',
    sourceGoals: ['verify_claim', 'reduce_self_threat'],
    preconditions: [],
    blockers: [],
    priorityBase: 0.02,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'verify_claim', weight: 0.6, clamp: [0, 1.0] },
      { kind: 'weighted_goal', goalId: 'reduce_self_threat', weight: 0.4, clamp: [0, 0.7] },
    ],
    groundingHints: ['observe', 'move', 'inspect'],
    tags: ['epistemic', 'space'],
  },

  {
    id: 'crosscheck_claim',
    family: 'epistemic',
    label: 'Перепроверить утверждение',
    description: 'Сопоставить версии и наблюдения, прежде чем действовать.',
    targeting: 'optional_other',
    sourceGoals: ['verify_claim'],
    preconditions: [],
    blockers: [],
    priorityBase: 0.02,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'verify_claim', weight: 0.9, clamp: [0, 1.4] },
    ],
    groundingHints: ['observe', 'question_about', 'share'],
    tags: ['verification'],
  },

  {
    id: 'clarify',
    family: 'communication',
    label: 'Прояснить',
    description: 'Снять недопонимание и удержать связность контакта.',
    targeting: 'other',
    sourceGoals: ['preserve_cooperation', 'maintain_trust_signal'],
    preconditions: [
      { kind: 'target_exists' },
      { kind: 'target_communicable', maxDistance: 5 },
    ],
    blockers: [],
    priorityBase: 0.03,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'preserve_cooperation', weight: 0.8, clamp: [0, 1.2] },
      { kind: 'weighted_goal', goalId: 'maintain_trust_signal', weight: 0.7, clamp: [0, 1.0] },
    ],
    groundingHints: ['talk', 'share', 'negotiate'],
    dialogueAct: 'inform',
    desiredEffect: 'share_information',
    tags: ['communication'],
  },

  {
    id: 'coordinate',
    family: 'coordination',
    label: 'Скоординироваться',
    description: 'Согласовать действия с нужным участником.',
    targeting: 'other',
    sourceGoals: ['preserve_cooperation', 'deescalate_interaction', 'protect_status_position', 'maintain_contact_channel'],
    preconditions: [
      { kind: 'target_exists' },
      {
        kind: 'any',
        conditions: [
          { kind: 'target_communicable', maxDistance: 5 },
          { kind: 'target_reachable', maxDistance: 8 },
        ],
      },
    ],
    blockers: [],
    priorityBase: 0.04,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'preserve_cooperation', weight: 0.7, clamp: [0, 1.2] },
      { kind: 'weighted_goal', goalId: 'maintain_contact_channel', weight: 0.6, clamp: [0, 1.0] },
      { kind: 'weighted_metric', metric: 'dependency', weight: 0.5, clamp: [0, 0.8] },
    ],
    groundingHints: ['talk', 'share', 'signal', 'move'],
    dialogueAct: 'inform',
    desiredEffect: 'obtain_commitment',
    tags: ['coordination'],
  },

  {
    id: 'apologize',
    family: 'communication',
    label: 'Извиниться',
    description: 'Восстановить канал доверия после напряжения.',
    targeting: 'other',
    sourceGoals: ['preserve_cooperation', 'maintain_trust_signal'],
    preconditions: [
      { kind: 'target_exists' },
      { kind: 'target_communicable', maxDistance: 4 },
    ],
    blockers: [],
    priorityBase: 0.01,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'maintain_trust_signal', weight: 0.9, clamp: [0, 1.0] },
    ],
    groundingHints: ['apologize', 'talk'],
    dialogueAct: 'inform',
    desiredEffect: 'repair_relation',
    tags: ['repair'],
  },

  {
    id: 'challenge_target',
    family: 'conflict',
    label: 'Оспорить цель',
    description: 'Силой или статусом ограничить нежелательное поведение другого.',
    targeting: 'other',
    sourceGoals: ['confront_threat_source', 'protect_status_position'],
    preconditions: [{ kind: 'target_exists' }],
    blockers: [{ kind: 'metric', metric: 'self_health', op: '<=', value: 0.15 }],
    priorityBase: 0.02,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'confront_threat_source', weight: 0.9, clamp: [0, 1.4] },
      { kind: 'weighted_goal', goalId: 'protect_status_position', weight: 0.5, clamp: [0, 0.8] },
    ],
    groundingHints: ['confront', 'threaten', 'command'],
    dialogueAct: 'accuse',
    desiredEffect: 'increase_compliance',
    tags: ['conflict'],
  },

  {
    id: 'threaten_target',
    family: 'conflict',
    label: 'Пригрозить цели',
    description: 'Добиться подчинения через угрозу.',
    targeting: 'other',
    sourceGoals: ['confront_threat_source'],
    preconditions: [{ kind: 'target_exists' }],
    blockers: [],
    priorityBase: 0.01,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'confront_threat_source', weight: 0.8, clamp: [0, 1.2] },
      { kind: 'weighted_metric', metric: 'authority', weight: 0.35, clamp: [0, 0.5] },
    ],
    groundingHints: ['threaten', 'talk'],
    dialogueAct: 'accuse',
    desiredEffect: 'increase_compliance',
    tags: ['threat'],
  },

  {
    id: 'attack_target',
    family: 'conflict',
    label: 'Атаковать цель',
    description: 'Физически нейтрализовать воспринимаемую угрозу.',
    targeting: 'other',
    sourceGoals: ['confront_threat_source'],
    preconditions: [
      { kind: 'target_exists' },
      { kind: 'target_reachable', maxDistance: 3 },
    ],
    blockers: [
      { kind: 'metric', metric: 'self_health', op: '<=', value: 0.12 },
    ],
    priorityBase: 0,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'confront_threat_source', weight: 1.0, clamp: [0, 1.6] },
    ],
    groundingHints: ['attack', 'move'],
    tags: ['physical_conflict'],
  },

  {
    id: 'command_target',
    family: 'communication',
    label: 'Приказать цели',
    description: 'Навязать координацию через статусное давление.',
    targeting: 'other',
    sourceGoals: ['confront_threat_source', 'protect_status_position'],
    preconditions: [
      { kind: 'target_exists' },
      { kind: 'target_communicable', maxDistance: 5 },
    ],
    blockers: [],
    priorityBase: 0.01,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'protect_status_position', weight: 0.7, clamp: [0, 1.1] },
      { kind: 'weighted_metric', metric: 'authority', weight: 0.5, clamp: [0, 0.7] },
    ],
    groundingHints: ['command', 'issue_order', 'talk'],
    dialogueAct: 'warn',
    desiredEffect: 'increase_compliance',
    tags: ['status', 'command'],
  },

  {
    id: 'pause',
    family: 'self_regulation',
    label: 'Остановиться',
    description: 'Снять перегрузку и не ухудшать состояние импульсивным действием.',
    targeting: 'self',
    sourceGoals: ['restore_self_control', 'recover_resources'],
    preconditions: [],
    blockers: [],
    priorityBase: 0.03,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'restore_self_control', weight: 0.8, clamp: [0, 1.2] },
      { kind: 'weighted_metric', metric: 'self_stress', weight: 0.5, clamp: [0, 0.7] },
    ],
    groundingHints: ['wait'],
    tags: ['rest'],
  },

  {
    id: 'breathe',
    family: 'self_regulation',
    label: 'Собраться / продышаться',
    description: 'Вернуть минимум самоконтроля без ухода из сцены.',
    targeting: 'self',
    sourceGoals: ['restore_self_control'],
    preconditions: [],
    blockers: [],
    priorityBase: 0.02,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'restore_self_control', weight: 0.7, clamp: [0, 1.0] },
    ],
    groundingHints: ['wait', 'self_treat'],
    tags: ['affect'],
  },

  {
    id: 'seek_support',
    family: 'communication',
    label: 'Искать поддержку',
    description: 'Обратиться к другому за стабилизацией или помощью.',
    targeting: 'other',
    sourceGoals: ['restore_self_control', 'maintain_contact_channel'],
    preconditions: [
      { kind: 'target_exists' },
      { kind: 'target_communicable', maxDistance: 5 },
    ],
    blockers: [],
    priorityBase: 0.02,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'restore_self_control', weight: 0.8, clamp: [0, 1.2] },
      { kind: 'weighted_metric', metric: 'self_stress', weight: 0.35, clamp: [0, 0.6] },
    ],
    groundingHints: ['talk', 'question_about', 'share'],
    dialogueAct: 'request_help',
    desiredEffect: 'obtain_commitment',
    tags: ['support'],
  },

  {
    id: 'share_signal',
    family: 'communication',
    label: 'Поддержать канал контакта',
    description: 'Послать краткий сигнал присутствия, связи или состояния.',
    targeting: 'other',
    sourceGoals: ['maintain_contact_channel'],
    preconditions: [
      { kind: 'target_exists' },
      {
        kind: 'any',
        conditions: [
          { kind: 'target_communicable', maxDistance: 6 },
          { kind: 'target_reachable', maxDistance: 8 },
        ],
      },
    ],
    blockers: [],
    priorityBase: 0.02,
    priorityRules: [
      { kind: 'weighted_goal', goalId: 'maintain_contact_channel', weight: 1.0, clamp: [0, 1.2] },
    ],
    groundingHints: ['signal', 'share', 'talk'],
    dialogueAct: 'inform',
    desiredEffect: 'share_information',
    tags: ['channel'],
  },
];
