import type { ContextAtom } from '../../context/v2/types';
import { normalizeAtom } from '../../context/v2/infer';
import { getMag } from '../../util/atoms';

const clamp01 = (x: number) => (Number.isFinite(x) ? Math.max(0, Math.min(1, x)) : 0);

function mk(selfId: string, otherId: string, metric: string, v: number, used: string[], parts: any): ContextAtom {
  return normalizeAtom({
    id: `tom:dyad:${selfId}:${otherId}:${metric}`,
    ns: 'tom',
    kind: 'tom_dyad' as any,
    origin: 'derived',
    source: 'tom_noncontext',
    subject: selfId,
    target: otherId,
    magnitude: clamp01(v),
    confidence: 1,
    tags: ['tom', 'dyad', metric],
    label: `tom.${metric}:${Math.round(clamp01(v) * 100)}%`,
    trace: { usedAtomIds: Array.from(new Set(used.filter(Boolean))), notes: ['rel:state -> tom:dyad'], parts }
  } as any);
}

/**
 * "Обычный ToM": минимальный слой, который всегда есть,
 * чтобы decision/actionPriors не зависели только от contextual ToM.
 *
 * Источник: rel:state:* (trust/hostility/closeness/respect/obligation).
 * + mem:episodic:* atoms (past significant events with this agent).
 */
export function deriveNonContextDyadAtoms(args: {
  selfId: string;
  otherIds: string[];
  atoms: ContextAtom[];
}): { atoms: ContextAtom[] } {
  const { selfId, otherIds, atoms } = args;
  const out: ContextAtom[] = [];

  for (const otherId of otherIds) {
    if (!otherId || otherId === selfId) continue;

    const idTrust = `rel:state:${selfId}:${otherId}:trust`;
    const idHost = `rel:state:${selfId}:${otherId}:hostility`;
    const idClos = `rel:state:${selfId}:${otherId}:closeness`;
    const idResp = `rel:state:${selfId}:${otherId}:respect`;
    const idObl = `rel:state:${selfId}:${otherId}:obligation`;

    let trust = clamp01(getMag(atoms, idTrust, 0.5));
    let host = clamp01(getMag(atoms, idHost, 0.0));
    const clos = clamp01(getMag(atoms, idClos, 0.2));
    const resp = clamp01(getMag(atoms, idResp, 0.0));
    const obl = clamp01(getMag(atoms, idObl, 0.0));

    // ── Episodic memory modulation ──
    // Scan mem:episodic atoms involving this other agent and shift
    // trust/hostility based on remembered significant events.
    // Atoms are generated by updateEpisodicMemory (perceiveActions.ts) and
    // injected into beliefAtoms by goalLabWorldState. Their magnitude is
    // already time-decayed (0.97^age), so recent events hit harder.
    const episodicUsed: string[] = [];
    const episodicPrefix = `mem:episodic:${selfId}:${otherId}:`;
    for (const a of atoms) {
      if (!a?.id?.startsWith(episodicPrefix)) continue;
      const mag = clamp01(Number((a as any)?.magnitude ?? 0));
      if (mag < 0.05) continue;
      episodicUsed.push(a.id);

      const kind = a.id.split(':')[4] || '';
      // Negative events erode trust and boost hostility.
      if (kind === 'trust_drop' || kind === 'betrayal') {
        trust = clamp01(trust - mag * 0.25);
        host = clamp01(host + mag * 0.20);
      } else if (kind === 'attack') {
        trust = clamp01(trust - mag * 0.15);
        host = clamp01(host + mag * 0.30);
      }
      // Positive events reinforce trust and reduce hostility.
      else if (kind === 'trust_gain' || kind === 'help') {
        trust = clamp01(trust + mag * 0.15);
        host = clamp01(host - mag * 0.10);
      }
    }

    // "Угроза" как функция враждебности + недоверия (простая, но стабильная).
    const threat = clamp01(0.70 * host + 0.30 * (1 - trust));

    const used = [idTrust, idHost, idClos, idResp, idObl, ...episodicUsed]
      .filter(id => atoms.some(a => a?.id === id));

    out.push(
      mk(selfId, otherId, 'trust', trust, used, { trust, host, clos, resp, obl, episodicCount: episodicUsed.length }),
      mk(selfId, otherId, 'threat', threat, used, { trust, host, episodicCount: episodicUsed.length }),
      mk(selfId, otherId, 'closeness', clos, used, { clos }),
      mk(selfId, otherId, 'respect', resp, used, { resp }),
      mk(selfId, otherId, 'obligation', obl, used, { obl })
    );
  }

  return { atoms: out };
}
