
import { ContextAtomKind } from './types';

/**
 * Runtime catalog of ContextAtomKind values.
 * TS union types are erased at runtime; GoalLab needs a concrete list to let the user
 * add/remove arbitrary atoms.
 */
export const CONTEXT_ATOM_KIND_CATALOG: ContextAtomKind[] = [
  // LEGACY / V2
  'physical_risk',
  'resource_availability',
  'social_visibility',
  'norm_pressure',
  'authority_presence',
  'support_available',
  'intimacy',
  'time_pressure',
  'proximity_friend',
  'proximity_enemy',
  'proximity_neutral',
  'target_presence',
  'care_need',
  'belief_leader_support',
  'belief_group_panicking',
  'belief_target_hostile',
  'belief_target_vulnerable',
  'belief_role_commander',
  'belief_role_medic',
  'belief_role_civilian',
  'belief_target_goal',
  'timeline_process',
  'environmental_hazard',
  'cover',
  'social_support',
  'threat',
  'proximity',
  'low_visibility_zone',
  'crowding_pressure',
  'safe_zone_hint',
  'emotion',
  'tom_belief',
  'threat_local',
  'threat_scene',
  'wounded_local',
  'wounded_scene',
  'ally_support',
  'enemy_threat',
  'isolation',
  
  // V4 DETAILED BODY (Interoception)
  'body_ok',
  'body_wounded',
  'body_low_stamina',
  'body_unarmed',
  'self_pain',
  'self_fatigue',
  'self_stress',
  'self_mobility_restricted',
  'self_hp',
  'self_stamina',
  'affect',

  // V4 DETAILED ToM
  'tom_trusted_ally_near',
  'tom_threatening_other_near',
  'tom_trust',
  'tom_threat',
  'tom_hostility',
  'tom_competence',
  'tom_support',
  'tom_attachment',
  'tom_closeness',
  'tom_respect',
  'tom_fear',
  'tom_confidence',
  'tom_bias_fear',
  'tom_bias_attach',
  
  // V4 MAP & DERIVED
  'hazard_local',
  'hazard_nearby',
  'presence_density',
  'closest_agent',
  'ally_needs_support',
  'trend_threat',
  'trend_support',
  'tom_other_severely_wounded',
  'tom_other_not_combat_capable',
  'location',
  'location_tag',
  'map_hazard',
  'map_cover',
  'map_exits',
  'nearby_agent',
  'nearby_agent_role',
  'wounded',
  'active_order',
  'global_threat_pressure',
  'global_social_pressure',
  'global_time_pressure',

  // V4 RICH LOCATION & AFFORDANCES
  'loc_id', 'loc_type', 'loc_tag', 'loc_owner',
  'env_hazard', 'env_visibility', 'env_noise', 'env_light', 'env_structural_integrity',
  'nav_exits_count', 'nav_exit_nearby', 'nav_chokepoints', 'nav_cover_mean', 'nav_cover_best', 'nav_obstacles_density', 'nav_paths_blocked',
  'soc_publicness', 'soc_surveillance', 'soc_norm_pressure', 'soc_status_asymmetry', 'soc_intimacy_support', 'soc_crowd_density',
  'cell_hazard', 'cell_cover', 'cell_visibility', 'cell_obstacle', 'cell_height', 'cell_exit', 'cell_interest',
  'local_best_cover', 'local_nearest_exit_distNorm', 'local_max_hazard', 'local_path_risk',
  'afford_hide', 'afford_escape', 'afford_observe', 'afford_talk_private', 'afford_talk_public', 'afford_rest', 'afford_treat_wounds', 'afford_command', 'afford_ritual', 'afford_trade', 'afford_search',

  // V4 NARRATIVE / EVENTS
  'event_recent',
  'event_threat',
  'event_support',
  'event_norm_violation',
];

export const DEFAULT_MANUAL_KINDS: ContextAtomKind[] = [
  'physical_risk',
  'social_visibility',
  'norm_pressure',
  'authority_presence',
  'intimacy',
  'time_pressure',
  'threat_scene',
  'threat_local',
  'soc_publicness',
  'soc_surveillance',
  'soc_crowd_density',
  'env_hazard',
  'env_visibility',
  'nav_exits_count',
  // Emotion/Appraisal overrides (for manual editing)
  'emotion_override',
  'appraisal_override',
];
